### ISSUE TITLE
How to Persist Data without using {{FrontSide}}?

### ISSUE THREAD

**Issue by adeluccar** [robbielaldrich/ankiTypebox#1]
Hey @robbielaldrich,

The add-on doesn't persist data if the ```{{typebox:}}``` tag is added to a *Back* card without using ```{{FrontSide}}```.

I'd like to be able to use the add-on to memorize coding snippets. Even without code highlighting, it would prove **tremendously helpful** to just write down the snippets and keep the state between the *Front* and *Back* cards.

Is there any way that this issue can be circumvented?

Note: I can't use the ```FrontSide``` tag because the code highlighting library ([highlight.js](highlightjs.org)) requires both a header script and a footer script. I load these on both sides of the card independently.

### Example Card Front

```html
<script src="_highlight.js"></script>

<div class="tag">
{{Tags}}
</div>

<div class="question">
{{#Refactor Problem}}
</div>

<div class="code">
<pre><code class="language-ruby">{{Code Snippet}}</code></pre>
</div>

{{typebox:}}

<script>
hljs.initHighlighting.called = false;
hljs.initHighlighting();
</script>
```

### Example Card Back

```html
<script src="_highlight.js"></script>

<div class="tag">
{{Tags}}
</div>

<div class="question">
{{#Refactor Problem}}
</div>

<div class="code">
<pre><code class="language-ruby">{{Code Snippet}}</code></pre>
</div>

{{typebox:}} <!-- This textarea box should persist data from the Front -->

<div class="code">
<pre><code class="language-ruby">{{Refactored Code Snippet}}</code></pre>
</div>

<script>
hljs.initHighlighting.called = false;
hljs.initHighlighting();
</script>
```

**Comment by robbielaldrich** [comment]
Hey, I'll look into this. Thanks.

**Comment by robbielaldrich** [comment]
Seems that the web view is being reloaded when not using the Front/Frontside/Back tags. Since the implementation saves what was entered in the textbox to a variable in the JS, it needs to keep the same web view for the back side of the card to know what was entered. I'm thinking about a refactor that would use QT and the Python code so the web view would not be needed -- maybe if I see more issues with other plugins like this down the line.

"Even without code highlighting, it would prove tremendously helpful to just write down the snippets and keep the state between the Front and Back cards."
So when you remove highlight.js and use the normal Front/Frontside/Back, it still doesn't persist the data from the front to the back textboxes?

**Comment by adeluccar** [comment]
Will double check and let you know. 👍🏻

**Comment by adeluccar** [comment]
Sorry! Finally got around at testing this (using a fresh default profile and deck). When that is the case, the plugin does work as advertised (even if `{{FrontSide}}` isn't used).

So in my particular case, I think that the plugin I'm using to be able to inject the highligh.js library must be interfering somehow ([js_booster](https://ankiweb.net/shared/info/1280253613)).

I'm going to close the issue for now (to avoid cluttering your issues). Unless you want to work at it (in which case, you're welcome to reopen it). I resorted to using an instance of Vim open while doing my programming ankis for my situation.
